"""Self-configuring connector scripts served to the Bloomberg Terminal computer.

A browser tab cannot talk to Bloomberg: ``blpapi`` is a native library that only
answers on ``localhost:8194`` of the machine running the Terminal. So one local
process is unavoidable. What *is* avoidable is every manual step around it — the
app bakes its own URL, the enrollment token and the terminal name into the script
it hands out, so the operator only runs a single pasted line.

Scripts are rendered with plain ``str.replace`` rather than ``str.format`` so the
PowerShell/Python bodies can keep their own braces untouched.
"""
from __future__ import annotations

from pathlib import Path


BRIDGE_SOURCE_PATH = Path(__file__).resolve().parents[3] / "tools" / "bloomberg_bridge" / "bridge.py"

# Kept in sync with tools/bloomberg_bridge/requirements.txt; xbbg is intentionally
# last so a blocked install still leaves the transport dependencies in place.
CONNECTOR_PIP_PACKAGES = ["requests", "pandas", "pyarrow", "xbbg"]


def bridge_source() -> str:
    """Return the bridge listener source shipped inside the API image."""
    return BRIDGE_SOURCE_PATH.read_text(encoding="utf-8")


_POWERSHELL_TEMPLATE = r'''# Bloomberg connector for __APP_NAME__
# Generated by the deployed app for terminal "__BRIDGE_ID__".
# This script only makes outbound HTTPS calls to __ENDPOINT__.

$ErrorActionPreference = "Stop"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$Endpoint    = "__ENDPOINT__"
$EnrollToken = "__TOKEN__"
$BridgeId    = "__BRIDGE_ID__"
$WorkDir     = Join-Path $env:LOCALAPPDATA "bt-bloomberg-bridge"

Write-Host ""
Write-Host "=== Bloomberg connector ===" -ForegroundColor Cyan
Write-Host "App      : $Endpoint"
Write-Host "Terminal : $BridgeId"
Write-Host "Folder   : $WorkDir"
Write-Host ""

New-Item -ItemType Directory -Force -Path $WorkDir | Out-Null

# Windows PowerShell 5.1 turns a native command's stderr into a terminating
# NativeCommandError while $ErrorActionPreference is "Stop". Every external call
# goes through this helper so a chatty pip cannot abort the connector.
function Invoke-Native {
  param([string]$Exe, [string[]]$Arguments)
  $previous = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  try {
    & $Exe @Arguments 2>&1 | Out-Null
    return $LASTEXITCODE
  } catch {
    return 1
  } finally {
    $ErrorActionPreference = $previous
  }
}

# Same protection, but the child's output stays visible to the operator.
function Invoke-NativeLoud {
  param([string]$Exe, [string[]]$Arguments)
  $previous = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  try {
    & $Exe @Arguments 2>&1 | ForEach-Object { Write-Host $_ }
    return $LASTEXITCODE
  } catch {
    Write-Host $_ -ForegroundColor Yellow
    return 1
  } finally {
    $ErrorActionPreference = $previous
  }
}

# --- 1. Locate a Python that can reach Bloomberg -----------------------------
function Find-Python {
  $candidates = @()
  $py = Get-Command py -ErrorAction SilentlyContinue
  if ($py) { $candidates += ,@($py.Source, @("-3")) }
  foreach ($name in @("python", "python3")) {
    $cmd = Get-Command $name -ErrorAction SilentlyContinue
    if ($cmd) { $candidates += ,@($cmd.Source, @()) }
  }
  foreach ($guess in @(
      "$env:LOCALAPPDATA\Programs\Python\Python312\python.exe",
      "$env:LOCALAPPDATA\Programs\Python\Python311\python.exe",
      "$env:LOCALAPPDATA\Continuum\anaconda3\python.exe",
      "$env:USERPROFILE\Anaconda3\python.exe",
      "C:\ProgramData\Anaconda3\python.exe",
      "C:\blp\API\APIv3\Python\python.exe")) {
    if (Test-Path -LiteralPath $guess) { $candidates += ,@($guess, @()) }
  }
  foreach ($candidate in $candidates) {
    if ((Invoke-Native $candidate[0] ($candidate[1] + @("-c", "import sys"))) -eq 0) { return $candidate }
  }
  return $null
}

$python = Find-Python
if ($null -eq $python) {
  throw "No usable Python found on this computer. Use the Jupyter option shown in the app instead."
}
$PythonExe  = $python[0]
$PythonArgs = $python[1]
Write-Host "[1/4] Python: $PythonExe" -ForegroundColor Green

# --- 2. Dependencies (best effort; blocked installs are not fatal) -----------
Write-Host "[2/4] Checking Python packages..." -ForegroundColor Green
foreach ($package in @(__PIP_PACKAGES__)) {
  if ((Invoke-Native $PythonExe ($PythonArgs + @("-c", "import $package"))) -ne 0) {
    Write-Host "      installing $package" -ForegroundColor DarkGray
    $code = Invoke-Native $PythonExe ($PythonArgs + @("-m", "pip", "install", "--quiet", "--user", $package))
    if ($code -ne 0) { Write-Host "      could not install $package (continuing)" -ForegroundColor Yellow }
  }
}

# --- 3. Download the listener and enroll this terminal -----------------------
$BridgePy = Join-Path $WorkDir "bridge.py"
Write-Host "[3/4] Downloading listener..." -ForegroundColor Green
Invoke-WebRequest -Uri "$Endpoint/bridge/bloomberg/connector/bridge.py?token=$EnrollToken" `
                  -OutFile $BridgePy -UseBasicParsing

$env:BT_BLOOMBERG_ENDPOINT = $Endpoint
$env:BT_BLOOMBERG_BRIDGE_ID = $BridgeId
$env:BT_BLOOMBERG_ENROLL_TOKEN = $EnrollToken

Write-Host "      enrolling terminal..." -ForegroundColor DarkGray
$enrollCode = Invoke-NativeLoud $PythonExe ($PythonArgs + @($BridgePy, "enroll", "--enroll-token", $EnrollToken))
if ($enrollCode -ne 0) { throw "Enrollment failed. Generate a new code in the app and retry." }
$env:BT_BLOOMBERG_ENROLL_TOKEN = $null

# --- 4. Stay connected -------------------------------------------------------
Write-Host ""
Write-Host "[4/4] Connected. Keep this window open while you use the Bloomberg tab." -ForegroundColor Cyan
Write-Host "      Close this window to disconnect the terminal." -ForegroundColor Yellow
Write-Host ""
while ($true) {
  Invoke-NativeLoud $PythonExe ($PythonArgs + @($BridgePy, "listen")) | Out-Null
  Write-Host "listener stopped; reconnecting in 15s..." -ForegroundColor DarkGray
  Start-Sleep -Seconds 15
}
'''


_PYTHON_TEMPLATE = r'''"""Bloomberg connector for __APP_NAME__ (terminal "__BRIDGE_ID__").

Paste into one Jupyter cell and run it. Only outbound HTTPS to __ENDPOINT__.
Interrupt the cell (stop button) to disconnect the terminal.
"""
import importlib
import os
import subprocess
import sys
import urllib.request

ENDPOINT = "__ENDPOINT__"
ENROLL_TOKEN = "__TOKEN__"
BRIDGE_ID = "__BRIDGE_ID__"
PACKAGES = [__PIP_PACKAGES__]

work_dir = os.path.join(os.path.expanduser("~"), ".bt-bloomberg-bridge")
os.makedirs(work_dir, exist_ok=True)

print("=== Bloomberg connector ===")
print("App      :", ENDPOINT)
print("Terminal :", BRIDGE_ID)
print("Folder   :", work_dir)

print("[1/3] Checking Python packages...")
for package in PACKAGES:
    try:
        importlib.import_module(package)
    except ImportError:
        print("      installing", package)
        try:
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "--quiet", "--user", package],
                check=True,
            )
        except Exception as exc:  # blocked installs must not stop the connector
            print("      could not install %s (%s) - continuing" % (package, exc))

print("[2/3] Downloading listener and enrolling...")
bridge_py = os.path.join(work_dir, "bridge.py")
with urllib.request.urlopen(
    "%s/bridge/bloomberg/connector/bridge.py?token=%s" % (ENDPOINT, ENROLL_TOKEN)
) as response:
    with open(bridge_py, "wb") as handle:
        handle.write(response.read())

os.environ["BT_BLOOMBERG_ENDPOINT"] = ENDPOINT
os.environ["BT_BLOOMBERG_BRIDGE_ID"] = BRIDGE_ID

sys.path.insert(0, work_dir)
bridge = importlib.import_module("bridge")
importlib.reload(bridge)

bridge.main(["enroll", "--enroll-token", ENROLL_TOKEN])

print("[3/3] Connected. Leave this cell running while you use the Bloomberg tab.")
try:
    bridge.main(["listen"])
except KeyboardInterrupt:
    print("Disconnected.")
'''


def _render(template: str, *, endpoint: str, token: str, bridge_id: str, app_name: str, quote: str) -> str:
    packages = ", ".join(f"{quote}{name}{quote}" for name in CONNECTOR_PIP_PACKAGES)
    return (
        template.replace("__ENDPOINT__", endpoint)
        .replace("__TOKEN__", token)
        .replace("__BRIDGE_ID__", bridge_id)
        .replace("__APP_NAME__", app_name)
        .replace("__PIP_PACKAGES__", packages)
    )


def render_powershell_connector(*, endpoint: str, token: str, bridge_id: str, app_name: str) -> str:
    return _render(
        _POWERSHELL_TEMPLATE,
        endpoint=endpoint,
        token=token,
        bridge_id=bridge_id,
        app_name=app_name,
        quote='"',
    )


def render_python_connector(*, endpoint: str, token: str, bridge_id: str, app_name: str) -> str:
    return _render(
        _PYTHON_TEMPLATE,
        endpoint=endpoint,
        token=token,
        bridge_id=bridge_id,
        app_name=app_name,
        quote='"',
    )


def powershell_one_liner(*, endpoint: str, token: str) -> str:
    """Single line to paste into a PowerShell window on the Bloomberg computer."""
    url = f"{endpoint}/bridge/bloomberg/connect.ps1?token={token}"
    return (
        "powershell -ExecutionPolicy Bypass -Command "
        f"\"iex (iwr '{url}' -UseBasicParsing).Content\""
    )


def python_one_liner(*, endpoint: str, token: str) -> str:
    """Single line to paste into a Jupyter cell on the Bloomberg computer."""
    url = f"{endpoint}/bridge/bloomberg/connect.py?token={token}"
    return f'import urllib.request; exec(urllib.request.urlopen("{url}").read().decode())'
